language: php

php:
    - 7.0
    - 7.1

before_install:
    - travis_retry composer self-update

install:
    - travis_retry composer update --prefer-dist --no-interaction

script:
    - vendor/bin/phpunit --no-configuration tests
